@DefineToken(name: "accent", value: "#7c5cff");
@DefineToken(name: "ink", value: "#2a2a2a");
@DefineToken(name: "muted", value: "#8a8a96");
@DefineToken(name: "background", value: "#f4f2fb");
@DefineToken(name: "card_background", value: "#ffffff");
@DefineToken(name: "footer_background", value: "#faf9fd");
@DefineToken(name: "border", value: "#ece9f3");
@DefineToken(name: "hairline", value: "#f1eff8");
@DefineToken(name: "company_name", value: "Example Company");
@DefineToken(name: "tagline", value: "Websites, SEO & growth systems for local businesses.");
@DefineToken(name: "company_address", value: "1209 Mountain Road Pl NE, Ste R, Albuquerque, NM 87110, USA");
@DefineToken(name: "logo_url", value: "https://growth.example.com/example-logo.png");
@DefineToken(name: "year", value: "2026");
